language: objective-c
before_install:
- gem install xcpretty -N cocoapods
script:
- set -o pipefail
- cd Support
- xcodebuild -project HockeySDK.xcodeproj -scheme "HockeySDK"
  -configuration Release -destination "platform=OS X" | xcpretty -c
